# Generated by Django 6.0.7 on 2026-09-15 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_convocatorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_identificacion', models.CharField(max_length=30)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=30)),
                ('centro_formacion', models.CharField(max_length=150)),
                ('regional', models.CharField(max_length=100)),
                ('archivo_pdf', models.FileField(upload_to='requisitos_inscripciones/')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='app_convocatorias.convocatoria')),
            ],
            options={
                'ordering': ['-fecha_inscripcion'],
            },
        ),
    ]
