# Generated by Django 6.0.7 on 2026-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_final', models.DateField()),
                ('ciudad', models.CharField(max_length=100)),
                ('cupos_totales', models.PositiveIntegerField()),
                ('cupos_asignados', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicada', 'Publicada'), ('Cerrada', 'Cerrada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=10)),
            ],
            options={
                'ordering': ['fecha_inicio'],
            },
        ),
    ]
